jobautoidx/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^', include('visualize.urls', namespace='visualize')),
    path('admin/$', admin.site.urls),
]

visualize/urls.py
from django.conf.urls import url
from . import views

app_name = 'visualize'
urlpatterns = [
    #url(r'^$', views.index.as_view(), name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^automation_index/$', views.automation_index, name='automation_index'),
    url(r'^automation_ranking/$', views.automation_ranking, name='automation_ranking'),
    url(r'^job_automation/$', views.job_automation, name='job_automation'),
    url(r'^skill_network/$', views.skill_network, name='skill_network'),        
    url(r'^skill_network_view/$', views.skill_network_view, name='skill_network_view'),        
    url(r'^skill_network_view_2008/$', views.skill_network_view_2008, name='skill_network_view_2008'),        
    url(r'^skill_network_view_mobile/$', views.skill_network_view_mobile, name='skill_network_view_mobile'),        

    url(r'^skill_network_view_network_only/$', views.skill_network_view_network_only, name='skill_network_view_network_only'),        

    url(r'^automation_map/$', views.automation_map, name='automation_map'),                
    url(r'^city_automation/$', views.city_automation, name='city_automation'),            
    url(r'^sitemap.xml/$', views.sitemap, name='sitemap'),
]

visualize/models.py
# -*- coding: utf-8 -*-
from django.utils import timezone
from django.db import models

visualize/forms.py
from django import forms
from django.conf import settings as djangoSettings
import pandas as pd

class JobAutomationIndexForm(forms.Form):
    csvpath = djangoSettings.STATICFILES_DIRS[0]+'/data/csv/jobs.csv'
    panel_df = pd.read_csv(csvpath, encoding='ISO-8859-1', dtype={'Family Code':str})

    panel_df_gp = panel_df.groupby('Family Code')

    JOBS = (u'(SOC 00) TOTAL AVERAGE', ((u'TOTAL AVERAGE', u'TOTAL AVERAGE'),)),

    for code, df in panel_df_gp:
        if code =='00':
            continue

        JOB = ()
        for i, r in df.iterrows():
            JOB = JOB + ((r['Job Title'], r['Job Title']),)

        JOBS = JOBS + (('(SOC '+code+') '+df.iloc[0]['Job Family'], JOB),)
        
    occupation = forms.ChoiceField(choices=JOBS, widget=forms.Select(attrs={'style': 'width:300px', 'class': 'autocomplete'}))

    #YEARS = (('2018', '2018'),('2008', '2008'),('2007~2018', '2007~2018'))
    YEARS = (('2020', '2020'),('2008', '2008'),('2008~2020', 'Change from 2008 to 2020'))
    
    year = forms.ChoiceField(choices=YEARS, widget=forms.Select(attrs={'style': 'width:250px', 'class': 'autocomplete'}))

class SkillDNA(forms.Form):
    csvpath = djangoSettings.STATICFILES_DIRS[0]+'/data/csv/jobs.csv'
    panel_df = pd.read_csv(csvpath, encoding='ISO-8859-1', dtype={'Family Code':str})

    panel_df_gp = panel_df.groupby('Family Code')

    JOBS = (u'(SOC 00) TOTAL AVERAGE', ((u'00-0000', u'TOTAL AVERAGE'),)),

    for code, df in panel_df_gp:
        if code =='00':
            continue

        JOB = ()
        for i, r in df.iterrows():
            JOB = JOB + ((r['Job Code'], r['Job Title']),)
        JOBS = JOBS + (('(SOC '+code+') '+df.iloc[0]['Job Family'], JOB),)

    occupation = forms.ChoiceField(choices=JOBS, widget=forms.Select(attrs={'style': 'width:300px', 'class': 'autocomplete'}))

    #YEARS = (('2007_2018', 'Evolution during 2007-2018'),('2018', '2018'),('2008', '2008'))
    YEARS = (('2020', '2020'),('2008', '2008'),('2008_2020', 'Change from 2008 to 2020'))
    year = forms.ChoiceField(choices=YEARS, widget=forms.Select(attrs={'style': 'width:250px', 'class': 'autocomplete'}))

class AutomationRanking(forms.Form):
    YEARS = (('2020', '2020'),('2008', '2008'),('2008~2020', 'Change from 2008 to 2020'))
    year = forms.ChoiceField(choices=YEARS, widget=forms.Select(attrs={'style': 'width:250px', 'class': 'autocomplete'}))        

class MapForm(forms.Form):
    TYPES = (("Race with the Machine","Race with the Machine"), 
             ("Race ahead of the Machine","Race ahead of the Machine"),
             ("Changing the Course of the Race","Changing the Course of the Race"),
             ("Race against the Machine","Race against the Machine"),
             ("Running a Different Race","Running a Different Race")) #("Changing the Course of a Race","Changing the Course of a Race")

    relation_to_automation = forms.ChoiceField(choices=TYPES, widget=forms.Select(attrs={'style': 'width:300px', 'class': 'autocomplete'}))

    YEARS = (('2020', '2020'),('2008', '2008'),('2008~2020', 'Change from 2008 to 2020'))
    
    year = forms.ChoiceField(choices=YEARS, widget=forms.Select(attrs={'style': 'width:250px', 'class': 'autocomplete'}))

visualize/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from  matplotlib import ticker

import numpy as np
from io import BytesIO
import base64

from django.http import JsonResponse

from .forms import JobAutomationIndexForm, SkillDNA, AutomationRanking, MapForm

from django.conf import settings as djangoSettings
import pandas as pd

def percentileofscore(a, score, kind='rank'):
    if np.isnan(score):
        return np.nan
    a = np.asarray(a)
    n = len(a)
    if n == 0:
        return 100.0

    if kind == 'rank':
        left = np.count_nonzero(a < score)
        right = np.count_nonzero(a <= score)
        pct = (right + left + (1 if right > left else 0)) * 50.0/n
        return pct
    elif kind == 'strict':
        return np.count_nonzero(a < score) / n * 100
    elif kind == 'weak':
        return np.count_nonzero(a <= score) / n * 100
    elif kind == 'mean':
        pct = (np.count_nonzero(a < score) + np.count_nonzero(a <= score)) / n * 50
        return pct
    else:
        raise ValueError("kind can only be 'rank', 'strict', 'weak' or 'mean'")

def draw_task_automation(year='2020', job='TOTAL AVERAGE'):
    #### TASK AUTOMATION ####
    csvpath = djangoSettings.STATICFILES_DIRS[0]+'/data/csv/Panel 1.csv'
    #panel_df = pd.read_csv(csvpath, encoding='ISO-8859-1', dtype={'Year':str})
    panel_df = pd.read_csv(csvpath, encoding='utf-8', dtype={'Year':str})

    if (year=='2020') or (year=='2008'):
        if job=='TOTAL AVERAGE':
            objects = ['Annual Wage', 'Race with the Machine', 'Race ahead of the Machine', 'Changing the Course of the Race',
                       'Race against the Machine', 'Running a Different Race']
        else:
            objects = ['Employment', 'Annual Wage', 'Race with the Machine', 'Race ahead of the Machine', 'Changing the Course of the Race',
                       'Race against the Machine', 'Running a Different Race']
    elif year=='2008~2020':
        if job=='TOTAL AVERAGE':
            objects = ['Race with the Machine Change', 'Race ahead of the Machine Change', 'Changing the Course of the Race Change',
                       'Race against the Machine Change', 'Running a Different Race Change', ]
        else:
            objects = ['Employment Share Change', 'Wage Share Change', 'Race with the Machine Change', 'Race ahead of the Machine Change', 'Changing the Course of the Race Change',
                       'Race against the Machine Change', 'Running a Different Race Change']

    if (year=='2020') or (year=='2008'):        
        fig, axs = plt.subplots(len(objects), figsize=(7,len(objects)*1.3))
        
        for i, obj in enumerate(objects):
            if ((obj =='Job Automation Index') or (obj =='Race with the Machine') or (obj =='Changing the Course of the Race') or 
                (obj =='Race against the Machine') or (obj =='Race ahead of the Machine') or (obj =='Running a Different Race')):

                val = panel_df[(panel_df['Year']==year)&(panel_df['Job Title']==job)][obj].iloc[0].tolist()
                val = val*100
                percentile = panel_df[(panel_df['Year']==year)&(panel_df['Job Title']==job)][obj+' Percentile'].iloc[0]
                #arr = panel_df[(panel_df['Year']==year)][obj].tolist()
                #percentile = percentileofscore(arr, val)

                axs[i].barh(0, val, align='center', alpha=0.5)
                axs[i].set_title(obj+' (%)')
                axs[i].set_yticklabels([])

                #axs[i].set_xlim(40, 60)
                #axs[i].set_xticks(np.arange(40,65,5))
                
                axs[i].set_xlim(0, 50)
                axs[i].set_xticks(np.arange(0,55,5))

                plt.setp(axs[i].get_xticklabels(), rotation=30)

                axs[i].text(0.9, 0.5, percentile, horizontalalignment='center',
                            verticalalignment='center', transform=axs[i].transAxes)
                #axs[i].text(0.9, 0.5, 'Top '+str(int(round(percentile/5.0)*5.0))+' %', horizontalalignment='center',
                #            verticalalignment='center', transform=axs[i].transAxes)

            elif obj =='Annual Wage':

                val = panel_df[(panel_df['Year']==year)&(panel_df['Job Title']==job)][obj].iloc[0].tolist()
                percentile = panel_df[(panel_df['Year']==year)&(panel_df['Job Title']==job)][obj+' Percentile'].iloc[0]
                #arr = panel_df[(panel_df['Year']==year)][obj].tolist()
                #percentile = percentileofscore(arr, val)
                

                axs[i].barh(0, val, align='center', alpha=0.5)
                #axs[i].barh(0, np.log2(val), align='center', alpha=0.5)

                #axs[i].set_xscale('log')
                axs[i].set_xscale('log', basex=2)

                axs[i].set_title(obj+' ($)')
                axs[i].set_yticklabels([])

                #axs[i].set_xlim(0, 300000)
                #axs[i].set_xlim(1, 3*1e5)
                axs[i].set_xlim(2**13, 2**18)

                #axs[i].set_xticklabels([format(label, ',.0f') for label in [10000,50000,100000,150000,200000,250000,300000]])
                axs[i].set_xticks([label for label in [10000,50000,100000,150000,200000,250000,300000]])
                axs[i].get_xaxis().set_major_formatter(ticker.ScalarFormatter())

                plt.setp(axs[i].get_xticklabels(), rotation=30)
                
                if job=='TOTAL AVERAGE':
                    axs[i].text(0.3, 0.5, 'Average Wage across All Jobs: ${:,}'.format(int(val)), horizontalalignment='left',
                                verticalalignment='center', transform=axs[i].transAxes)
                else:                
                    axs[i].text(0.9, 0.5, percentile, horizontalalignment='center',
                            verticalalignment='center', transform=axs[i].transAxes)
                #axs[i].text(0.9, 0.5, 'Top '+str(int(round(percentile/5.0)*5.0))+' %', horizontalalignment='center',
                #            verticalalignment='center', transform=axs[i].transAxes)

            elif obj == 'Employment':
                val = panel_df[(panel_df['Year']==year)&(panel_df['Job Title']==job)][obj].iloc[0].tolist()
    
                percentile = panel_df[(panel_df['Year']==year)&(panel_df['Job Title']==job)][obj+' Percentile'].iloc[0]
                #arr = panel_df[(panel_df['Year']==year)][obj].tolist()
                #percentile = percentileofscore(arr, val)

                axs[i].barh(0, val, align='center', alpha=0.5)
                #axs[i].barh(0, val, align='center', alpha=0.5)

                axs[i].set_xscale('log')
                
                axs[i].set_title(obj)
                axs[i].set_yticklabels([])

                #axs[i].set_xlim(0, 5000000)
                #axs[i].set_xlim(1, 5*1e6)
                axs[i].set_xlim(10**2, 10**7)
                #axs[i].set_xlim(100, 1000000)                

                #axs[i].set_xticklabels([format(label, ',.0f') for label in [100,1000,10000,100000,1000000,10000000,50000000]])
                axs[i].set_xticks([label for label in [100,1000,10000,100000,1000000,10000000,50000000]])
                #axs[i].get_xaxis().set_major_formatter(ticker.ScalarFormatter())
                axs[i].get_xaxis().set_major_formatter(ticker.FormatStrFormatter("%d"))

                plt.setp(axs[i].get_xticklabels(), rotation=30)
                
                axs[i].text(0.9, 0.5, percentile, horizontalalignment='center',
                            verticalalignment='center', transform=axs[i].transAxes)
                #axs[i].text(0.9, 0.5, 'Top '+str(int(round(percentile/5.0)*5.0))+' %', horizontalalignment='center',
                #            verticalalignment='center', transform=axs[i].transAxes)

        plt.tight_layout()

    elif year=='2008~2020':

        if len(objects) == 2:
            fig, axs = plt.subplots(len(objects), figsize=(7,2*1.3))
            
            for i, obj in enumerate(objects):
                if ((obj =='Job Automation Index Change') or (obj =='Race with the Machine Change') or (obj =='Changing the Course of the Race Change') or 
                    (obj =='Race against the Machine Change') or (obj =='Race ahead of the Machine Change') or (obj =='Running a Different Race Change')):

                    val = panel_df[(panel_df['Year']==year)&(panel_df['Job Title']==job)][obj].iloc[0].tolist()
                    val = val*100

                    percentile = panel_df[(panel_df['Year']==year)&(panel_df['Job Title']==job)][obj+' Percentile'].iloc[0]
                    #arr = panel_df[(panel_df['Year']==year)][obj].tolist()
                    #percentile = percentileofscore(arr, val)

                    axs[i].barh(0, val, align='center', alpha=0.5)
                    axs[i].set_title(obj+' (%p)')
                    axs[i].set_yticklabels([])

                    #axs[i].set_xlim(-5, 5)
                    #axs[i].set_xticks(np.arange(-5,6,1))
                    axs[i].set_xlim(-17,17)
                    axs[i].set_xticks(np.arange(-17,18,1))

                    ax_xtick = axs[i].get_xticks().tolist() 
                    ax_xtick[0] = '<-5'
                    ax_xtick[-1] = '5<'
                    axs[i].set_xticklabels(ax_xtick)            
                    
                    plt.setp(axs[i].get_xticklabels(), rotation=30)

                    axs[i].text(0.9, 0.5, percentile, horizontalalignment='center',
                                verticalalignment='center', transform=axs[i].transAxes)
                    #axs[i].text(0.9, 0.5, 'Top '+str(int(round(percentile/5.0)*5.0))+' %', horizontalalignment='center',
                    #            verticalalignment='center', transform=axs[i].transAxes)
                    
                elif obj == 'Wage Share Change':

visualize/templates/visualize/about.html
{% extends "visualize/layout.html" %}
{% load static %}
{% block content %}

<div class="card mb-3" style="max-width: 1200px;">
<div class="card-header">
    About
</div>

<div class="card-body" style="text-align: justify;">
    <h5 style="text-align: center;"><strong><em>A Data-Driven Exploration of the Race between Human Labor and Machines</em></strong></h5> </br>
        <p style="text-align: right;">“If you can’t measure it, you can’t manage it.” </p>
        <p style="text-align: right;">-	Peter Drucker</p>

        <div class="embed-responsive embed-responsive-16by9">
            <!--<iframe width="640" height="360" class="embed-responsive-item" src="https://player.vimeo.com/video/700520130" allowfullscreen></iframe>-->
            <iframe width="100%" height="500" src="https://player.vimeo.com/video/700520130" allowfullscreen></iframe>
        </div>

</br>

Anxiety about automation is prevalent in this era of rapid technological advances, especially in artificial intelligence, machine learning, and robotics. Accordingly, how human labor competes, or cooperates, with the machine in performing a range of tasks (what we term “<b>the race between human labor and machines</b>”) has attracted a great deal of attention among the public, policymakers, and researchers.

</br></br>
While there have been persistent concerns about new technology and automation replacing human tasks at least since the Industrial Revolution, recent technological advances in executing sophisticated and complex tasks—enabled by a combinatorial innovation of new techniques and algorithms, advances in computational power, and exponential increase in data—differentiate the 21st century from previous ones. However, the oft-overlooked reality is that technology directly affects the demand for specific skills or tasks, instead of acting on occupations as a whole, and not all types of tasks are displaced by technology. Rather, technology can substitute for some human tasks, but can also augment human intelligence and complement specific types of tasks in ways that lead to higher demand for occupations in which those tasks are performed. The tension between automation and augmentation has been discussed in research and industry alike. Thus, a full picture of automation and the future of work requires a task-level, rather than occupation-level, understanding of not only technological change—to what extent a human task is automated—but also labor demand for occupations performing a task in recent years. To this end, we propose a data-driven methodology to scrutinize which tasks are more susceptible or complementary to automation in the 21st century, with respect to (i) changes in degree of automation and (ii) changes in employment share.
</br></br>
By representing occupational skill requirements as a network, we reveal 15 endogenous task types which are clusters of related skills required to a similar extent by occupations, as shown below.
</br></br>

<img src="{% static 'img/Skill_Network.png' %}" class="img-fluid">

We then measure each task’s degree of automation in 2008 and 2020, respectively. Based on changes in degree of automation and employment share from 2008 to 2020, the task types are classified into five distinct categories as follows, highlighting that the increase in automation level does not always lead to a decrease in labor demand for the task.
</br></br>

<img src="{% static 'img/Job Automation Index_2021v2.png' %}" class="img-fluid">

<div class="small text-muted">Note that the point size is proportional to the degree of automation in 2020. </div></br></br>

<ul>
    <li><b>Race with the Machine</b>: Tasks have experienced an increase in automation level, while the employment share for the tasks has increased from 2008 to 2020</li>
    <li><b>Race ahead of the Machine</b>: Tasks have experienced a decrease in automation level, while the employment share for the tasks has increased from 2008 to 2020</li>
    <li><b>Changing the Course of the Race</b>: Tasks were already highly automated in 2020, but have experienced a decrease in automation level, while the employment share for the tasks has decreased from 2008 to 2020</li>
    <li><b>Race against the Machine</b>: Tasks have experienced an increase in automation level, while the employment share for the tasks has decreased from 2008 to 2020</li>
    <li><b>Running a Different Race</b>: Tasks have experienced an increase in automation level, while the employment share for the tasks has remained relatively stable during 2008–2020</li>
</ul>

Based on an occupation’s task content and a city’s occupational composition, we construct a task-level job automation index for representative occupations and a task-level city automation index for U.S. cities. The proposed automation indexes are found to be significantly correlated with occupational characteristics (e.g., suitability for machine learning, telework and offshoring) and regional characteristics for innovation capacity. The findings highlight that task-level automation indexes provide a granular understanding of how automation affects occupations and communities.
</br></br>

Based on our analysis, we develop a website for the automation indexes to facilitate discussion and communications on the impacts of automation: www.jobautomationindex.com. The website offers an interactive interface for the task-level degree of automation across occupations and U.S. cities for the following menus:
</br></br>

<p style="text-align: left;">
    &nbsp; (1)	<a href="{% url 'visualize:automation_index'%}">Job Automation Index </a></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Demonstrate an occupation’s job automation index</br>
    &nbsp; (2)	<a href="{% url 'visualize:skill_network'%}">Skill Network</a></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Visualize an occupation’s skill requirements and degree of automation</br>    
    &nbsp; (3)	<a href="{% url 'visualize:job_automation'%}">Task-Level Job Automation </a></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sort all occupations by task-level job automation index</br>
    &nbsp; (4)	<a href="{% url 'visualize:automation_map'%}">Automation Map (U.S. Cities)</a></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Visualize a city’s degree of automation in the United States</br>
    &nbsp; (5)	<a href="{% url 'visualize:city_automation'%}">Task-Level City Automation</a></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sort all U.S. cities by task-level city automation index</br>    
</p>

The entire source code is publicly accessible to encourage reproducibility at <a href="https://github.com/jonghkim/job-automation-index">GitHub Link</a>. 

Please see <a href="https://cacm.acm.org/magazines/2022/5/260356-a-data-driven-exploration-of-the-race-between-human-labor-and-machines-in-the-21st-century/fulltext">our research paper</a> for detailed descriptions behind the job automation index. 

We welcome any comments and feedback on the research project and the website for job automation index.</br></br>

</div>
</div>
{% endblock %}

visualize/templates/visualize/city_selector.html
{% load static %}
<div class="card mb-3">
<div class="card-header">
    Selection
</div>

<div class="card-body">
    <form method="POST" class="post-form">
        {%csrf_token%}
        <!--{{form.as_table}}-->
        
        {% for field in form %}
        <tr><td>{{ field.label_tag }} {{field}}</td></tr> &nbsp;
        {% endfor %}

        <!--        
            {% for field in form %}
            <tr><td>{{field}}</td></tr>
            {% endfor %}
        </table>
        -->
        <button type="submit" class="btn-primary" style="background-color:#13A2DC; border: none !important;">&nbsp;&nbsp; Submit &nbsp;&nbsp;</button>
    </form>
</div>
</div>

<style>
li {
    display:inline !important;
    list-style-type: none;
    padding-right: 10px;    
}
</style>

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

<script>
$(document).ready(function(){
    var occupation_button = $("#id_occupation"),
        parent_width = $(document).width()*0.5;
    $(window).on("resize", function() {
        if(parent_width > 300) {
            var occupation_targetWidth = 300;
        }
        else{
            var occupation_targetWidth = parent_width;
        }
        occupation_button.css('width',occupation_targetWidth);
    }).trigger("resize");

    var year_button = $("#id_year"),
        parent_width = $(document).width()*0.5;
    $(window).on("resize", function() {
        if(parent_width > 200) {
            var year_targetWidth = 200;
        }
        else{
            var year_targetWidth = parent_width;
        }
        year_button.css('width',year_targetWidth);
    }).trigger("resize");
});
</script>

visualize/templates/visualize/job_automation.html
{% extends "visualize/layout.html" %}

{% load static %}

{% block content %}

{% include "visualize/job_automation_selector.html" %} 

<!-- Panel4 -->
{% include "visualize/panel4.html" %} 
<!-- /#panel4-wrapper -->

{% endblock %}

visualize/templates/visualize/map_automation.html
{% extends "visualize/layout.html" %}

{% load static %}

{% block content %}

{% include "visualize/map_selector.html" %} 

<!-- Panel3 -->
{% include "visualize/panel6.html" %} 
<!-- /#panel3-wrapper -->
{% endblock %}

visualize/templates/visualize/skill_network_selector.html
{% load static %}
<link href="{% static 'css/select2.min.css' %}" rel="stylesheet" />
<script src="{% static 'js/select2.min.js' %}" defer></script>

<div class="card mb-3">
<div class="card-header">
    Selection
</div>

<div class="card-body">
    <form method="POST" class="post-form">
        {%csrf_token%}
        
        {% for field in form %}
        <tr><td>{{ field.label_tag }} {{field}}</td></tr> &nbsp;
        {% endfor %}
        <button type="submit" class="btn-primary" style="background-color:#13A2DC; border: none !important;">&nbsp;&nbsp; Submit &nbsp;&nbsp;</button>
    </form>
</div>
</div>

<style>
form {display:none;}

#id_occupation{
    width: 300px;

}    
#id_year{
    width: 250px;

}
@media only screen and (max-width: 750px) {
    #id_occupation {
        width: 30vw !important;
    }        
    #id_year {
        width: 30vw !important;
    }    
}
.select2{
    width: 300px;
}
@media only screen and (max-width: 750px) {
    .select2 {
        width: 50vw !important;
        font-size: small;
    }
    .select2-results__options{
        width: 50vw !important;
        font-size: small;        
    }
}  
</style>

<script>
    $(document).ready(function() {
        $('.autocomplete').select2();
        $('form').css("display","inline");  
    });      
</script>

visualize/templates/visualize/task_level_automation_selector.html
{% load static %}

<link href="{% static 'css/select2.min.css' %}" rel="stylesheet" />
<script src="{% static 'js/select2.min.js' %}" defer></script>

<div class="card mb-3">
<div class="card-header">
    Selection
</div>

<div class="card-body">
    <form method="POST" class="post-form">
        {%csrf_token%}
        <!--{{form.as_table}}-->
        
        {% for field in form %}
        <tr><td>{{ field.label_tag }} {{field}}</td></tr> &nbsp;
        {% endfor %}

        <!--
        
            {% for field in form %}
            <tr><td>{{field}}</td></tr>
            {% endfor %}
        </table>
        -->
        <button type="submit" class="btn-primary" style="background-color:#13A2DC; border: none !important;">&nbsp;&nbsp; Submit &nbsp;&nbsp;</button>
    </form>
</div>
<div class="card-footer small text-muted">
    &middot; Race with the Machine: Tasks that have experienced in the increase in degree of automation but complemented labor demands during 2007-2019 </br>
    &middot; Race against the Machine: Tasks that have experienced in the increase in degree of automation and substituted labor demands during 2007-2019 </br>
    &middot; Race ahead of the Machine: Tasks that have experienced in the decrease in degree of automation and complemented labor demands during 2007-2019 </br>
    &middot; Running a Different Race: Tasks that are seemingly unrelated to labor demands during 2007-2019, regardless of changes in degree of automation </br>
</div>
</div>

<style>
form {display:none;}
    
#id_year{
    width: 250px;

}
@media only screen and (max-width: 750px) {
    #id_year {
        width: 30vw !important;
    }    
}
.select2{
    width: 300px;
}
@media only screen and (max-width: 750px) {
    .select2 {
        width: 50vw !important;
        font-size: small;
    }
    .select2-results__options{
        width: 50vw !important;
        font-size: small;        
    }
}  
</style>


<script>
    $(document).ready(function() {
        $('.autocomplete').select2();
        $('form').css("display","inline");  
    }); 
</script>